# Generated by Django 4.2.1 on 2023-06-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="certificate",
            field=models.FileField(null=True, upload_to="certificates/"),
        ),
    ]
