# Generated by Django 4.2.1 on 2023-06-09 17:37

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_student_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="certificate",
            field=models.ImageField(
                null=True, upload_to=blog.models.upload_certificate
            ),
        ),
    ]
